# CONFIGURACIÓN PRINCIPAL

# Tipo de bloque considerado "falso" que se romperá al pisarse.
# Por defecto: TINTED_GLASS
block-to-break: "TINTED_GLASS"

# Retardo en ticks antes de que se rompa la plataforma (20 ticks = 1 segundo).
break-delay: 10

# Si se aplica en 2D (solo en la capa del bloque) o en 3D (incluye arriba/abajo).
# true = solo misma altura (4 direcciones), false = en 3D (6 direcciones).
search-in-2d: true

# ¿El jugador muere automáticamente al pisar la plataforma?
kill-player: false

# ¿Restringir el efecto a una zona del mundo?
# Si es false, se romperá cualquier TINTED_GLASS en cualquier parte.
# Si es true, solo romperá dentro del rectángulo minX..maxX y minZ..maxZ en el mundo dado.
restricted-area: false
restricted-world: "world"
minX: 100
maxX: 200
minZ: 100
maxZ: 200

# Mensajes al jugador
message-on-step: "§c¡Has pisado cristal falso! Toda la plataforma se romperá..."
message-on-break: "§7La plataforma se ha roto..."
message-on-death: "§4¡Has muerto al pisar el bloque falso!"
