name: Glassgame
version: 1.0
main: am.FroshGames.glassgame.Glassgame
author: FroshGames
api-version: 1.20
description: Plugin de "Glassgame", rompe bloques falsos al pisarlos.

commands:
  glassgame:
    description: Comando principal para gestionar el plugin.
    usage: /glassgame [start|stop|help]
